# Generated by Django 4.2.27 on 2025-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('user', 'sku'), name='unique_sku_per_user'),
        ),
    ]
